### PR TITLE
Test against python3.6

### PR DESCRIPTION
**Pull request by asottile**
At the very least this gets the ball rolling

### CODE REVIEW

**Comment by sigmavirus24** [comment]
I suspect we also need to test for `ANNASSIGN` and other new bits in 3.6

**Comment by asottile** [comment]
I'll add a test for them, I don't think they affect the complexity output but perhaps the dot output

**Comment by sigmavirus24** [comment]
@asottile as an AST visitor if we don't have a way to visit it then it'll crash, much like PyFlakes.

**Comment by asottile** [comment]
That's not my experience with ast visitors, and not the behaviour of mccabe:

```
$ cat test.py
def f():
    y: Any = None
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.eggs/
	after
	before
	patch
	test.py

nothing added to commit but untracked files present (use "git add" to track)
$ python3.6 mccabe.py test.py
1:0: 'f' 2
```

It is however reporting incorrectly so I will add a test and fix it.

As an aside, the trivial `ast.NodeVisitor` does not crash:

```python
>>> import ast
>>> visitor = ast.NodeVisitor()
>>> visitor.visit(ast.parse('x = 5\ny : Any = 5\n'))
>>> 
```

**Comment by asottile** [comment]
I've added support for annotated assignments.

From the other syntax changes:
- [f-strings](https://docs.python.org/3.6/whatsnew/3.6.html#pep-498-formatted-string-literals) - mccabe does not consider values, only statements and control flow
- [undescores in integer literals](https://docs.python.org/3.6/whatsnew/3.6.html#pep-515-underscores-in-numeric-literals) - ""
- [async generators](https://docs.python.org/3.6/whatsnew/3.6.html#pep-525-asynchronous-generators) - Does not affect mccabe, the `await ...` statement is already handled
- [async comprehensions](https://docs.python.org/3.6/whatsnew/3.6.html#pep-530-asynchronous-comprehensions) - Does not affect mccabe, mccabe does not consider comprehensions for statements or complexity

**Comment by asottile** [comment]
Oh right I confliced with myself heh :)

Fortunately my other patch makes the second commit of this into "just add a test"!

**Pull request merged**
