### PR TITLE
Make signatures of default method match

### PR DESCRIPTION
**Pull request by degustaf**
PathGraphingAstVisitor inherits from ASTVisitor, but they have different signatures.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
@degustaf sorry about the tests. Travis-CI seems to have broken how they parse their configuration file. I've emailed them in the hopes they'll fix it.

As a last resort, I'm going to close and reopen this to trigger a *new* build.

**Comment by sigmavirus24** [comment]
They fixed it and the close/reopen worked!

**Comment by sigmavirus24** [comment]
@degustaf was this causing problems for you? Should we cut a 0.6.1?

**Comment by degustaf** [comment]
It is causing a pylint error in [pylint](https://github.com/PyCQA/pylint) where PathGraphingAstVisitor is being subclassed and default is overwritten.

**Comment by sigmavirus24** [comment]
PyLint really should be capping versions to avoid problems like this. I'll schedule a 0.6.1 release for later

**Pull request merged**
